// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awktmolfeyjgjhbezils.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3a3Rtb2xmZXlqZ2poYmV6aWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTMyMDQsImV4cCI6MjA2NzcyOTIwNH0.PWoz9RPLTXByBfdmI_MaCmGsuuhYW92D9-RKzl_9WH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});